### Создание кошелька для случайного пользователя
POST http://localhost:8080/api/wallets
Content-Type: application/x-www-form-urlencoded

userId=1

### Пополнение баланса на 100 для пользователя с id 1
PUT http://localhost:8080/api/wallets/1/top-up
Content-Type: application/x-www-form-urlencoded

amount=100

### Получение баланса для пользователя с id 1
GET http://localhost:8080/api/wallets/1/balance




### Создание кошелька для случайного пользователя через контейнер
POST http://localhost:7070/api/wallets
Content-Type: application/x-www-form-urlencoded

userId={{$randomInt}}

### Пополнение баланса на 100 для пользователя с id 1 через контейнер
PUT http://localhost:7070/api/wallets/1/top-up
Content-Type: application/x-www-form-urlencoded

amount=100

### Получение баланса для пользователя с id 1 через контейнер
GET http://localhost:7070/api/wallets/1/balance